In [1]:
import numpy as np
i = np.array([10,20,30,40,50])
j = i.copy()
i[0] = 100
i[1] = 200

print(i)
print(j)

[100 200  30  40  50]
[10 20 30 40 50]


In [2]:
import numpy as np
i = np.array([1,2,3,4,5,6])
j = i.view()

i[0] = 10
i[1] = 20

print(i)
print(j)

[10 20  3  4  5  6]
[10 20  3  4  5  6]


In [3]:
import numpy as np
i = np.array([1,2,3,4,5.6])
j = i.view()

j[0] = 10
j[1] = 20

print(i)
print(j)
print()

print(i.base)
print(j.base)


[10.  20.   3.   4.   5.6]
[10.  20.   3.   4.   5.6]

None
[10.  20.   3.   4.   5.6]


In [4]:
import numpy as np

i = np.array([10,20,30,40,50,60])

print(i.shape)


(6,)


In [6]:
import numpy as np

i = np.array([[1,2,3,4,5,6],
             [7,8,9,10,11,12]])

print(i)
print(i.shape)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)


In [7]:
import numpy as np

i = np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]],
             [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])

print(i.shape)

(2, 3, 5)


In [11]:
import numpy as np

i = np.array([10,20,30,40,50,60,70,80,90,100,110,120])

j = i.reshape(4,3)

j

array([[ 10,  20,  30],
       [ 40,  50,  60],
       [ 70,  80,  90],
       [100, 110, 120]])

In [13]:
import numpy as np

i = np.array([10,20,30,40,50,60,70,80,90,100,110,120,130,140,150,160])

j = i.reshape(2,2,4)

j

array([[[ 10,  20,  30,  40],
        [ 50,  60,  70,  80]],

       [[ 90, 100, 110, 120],
        [130, 140, 150, 160]]])

In [20]:
import numpy as np

i = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])

j = (i.reshape(2,5,2))

j

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [21]:
j = i.reshape(2,5,-1)

j

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

In [22]:
import numpy as np

i = np.array([[10,20,30],[40,50,60],[70,80,90]])

j = i.reshape(-1)

j

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [23]:
import numpy as np

i = np.array([10,20,30,40,50,60,70])

for j in i:
    print(j)

10
20
30
40
50
60
70


In [24]:
import numpy as np

i = np.array([[1,2,3],[4,5,6],[7,8,9]])

for j in i:
    print(j)

[1 2 3]
[4 5 6]
[7 8 9]


In [25]:
for j in i:
    for k in j:
        print(k)

1
2
3
4
5
6
7
8
9


In [26]:
import numpy as np

i = np.array([[[1,2,3],[4,5,6],[7,8,9]],
             [[10,20,30],[40,50,60],[70,80,90]],
             [[11,22,33],[44,55,66],[77,88,99]],
             ])

for j in i:
    print(j)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[11 22 33]
 [44 55 66]
 [77 88 99]]


In [27]:
for j in i:
    for k in j:
        for m in k:
            print(m)

1
2
3
4
5
6
7
8
9
10
20
30
40
50
60
70
80
90
11
22
33
44
55
66
77
88
99


In [29]:
from numpy import random

i = random.randint(100)

print(i)


97


In [30]:
from numpy import random

i = random.rand()

print(i)

0.07565251239796988


In [32]:
from numpy import random

i = random.rand(5)

print(i)

[0.15600732 0.20052378 0.91059329 0.09216735 0.11479993]


In [34]:
from numpy import random

i = random.randint(100,size=(10))

i

array([44,  2, 85, 70, 53,  3, 95, 89, 81, 76])

In [35]:
i = random.randint(100,size=(4,5))

i

array([[73, 83, 84, 19, 55],
       [29, 51, 64, 23, 57],
       [13, 21,  3, 45, 42],
       [97, 38,  3, 85, 56]])

In [36]:
i = random.randint(100,size=(2,4,5))

i

array([[[82, 26, 12, 59, 50],
        [ 1,  9, 19, 89,  3],
        [36, 10, 29, 66, 72],
        [ 4, 57, 31, 74, 39]],

       [[ 5,  4, 59, 43, 30],
        [35,  6, 21, 14, 22],
        [98,  6, 93, 87,  8],
        [35, 92, 29, 85, 53]]])

In [37]:
from numpy import random

list1 = [1,2,3,4,5,6,7,8,9,10]

i = random.choice(list1)

i

4

In [38]:
from numpy import random

i = random.randint(50,size=(5))

i

array([26,  8, 22, 35, 48])